import type {
  ProjectSummary,
  ProjectItem,
  OperationItem,
} from "@/types/project.types";

// TF 프로젝트 요약 목업 데이터
export const mockTfSummary: ProjectSummary = {
  count: 4,
  completed: 85,
  updated: 109,
  created: 32,
};

// 운영 요약 목업 데이터
export const mockOperationSummary: ProjectSummary = {
  count: 21,
  completed: 454,
  updated: 1109,
  created: 532,
};

// TF 프로젝트 목록 목업 데이터
export const mockTfProjects: ProjectItem[] = [
  {
    id: "1",
    name: "사용자 인증 시스템 고도화",
    epicId: "EPIC-1001",
    epicUrl: "https://jira.example.com/browse/EPIC-1001",
    activeTicketCount: 10,
    bugCount: 5,
    incidentCount: 2,
    avgResolutionTime: 3.2,
    avgDetectionTime: 22,
    avgDiagnosisTime: 1.5,
    avgRecoveryTime: 1.7,
    createdAt: "2025.12.01",
  },
  {
    id: "2",
    name: "결제 모듈 성능 개선",
    epicId: "EPIC-1002",
    epicUrl: "https://jira.example.com/browse/EPIC-1002",
    activeTicketCount: 7,
    bugCount: 3,
    incidentCount: 1,
    avgResolutionTime: 2.8,
    avgDetectionTime: 18,
    avgDiagnosisTime: 1.2,
    avgRecoveryTime: 1.6,
    createdAt: "2025.12.01",
  },
  {
    id: "3",
    name: "알림 시스템 리팩토링",
    epicId: "EPIC-1003",
    epicUrl: "https://jira.example.com/browse/EPIC-1003",
    activeTicketCount: 2,
    bugCount: 2,
    incidentCount: 0,
    avgResolutionTime: null,
    avgDetectionTime: null,
    avgDiagnosisTime: null,
    avgRecoveryTime: null,
    createdAt: "2025.12.01",
  },
  {
    id: "4",
    name: "데이터 마이그레이션",
    epicId: "EPIC-1004",
    epicUrl: "https://jira.example.com/browse/EPIC-1004",
    activeTicketCount: 2,
    bugCount: 7,
    incidentCount: 3,
    avgResolutionTime: 4.1,
    avgDetectionTime: 35,
    avgDiagnosisTime: 2.3,
    avgRecoveryTime: 1.8,
    createdAt: "2025.12.01",
  },
];

// 운영 에픽 목록 목업 데이터
export const mockOperationItems: OperationItem[] = [
  {
    id: "1",
    name: "결제 시스템 긴급 패치",
    epicId: "OPR2-1234",
    epicUrl: "https://jira.example.com/browse/OPR2-1234",
    activeTicketCount: 10,
    updatedCount: 2,
    completedCount: 3,
    createdCount: 5,
    createdAt: "2025.10.05",
  },
  {
    id: "2",
    name: "회원 가입 오류 수정",
    epicId: "OPR2-1235",
    epicUrl: "https://jira.example.com/browse/OPR2-1235",
    activeTicketCount: 20,
    updatedCount: 5,
    completedCount: 5,
    createdCount: 5,
    createdAt: "2025.10.08",
  },
  {
    id: "3",
    name: "알림 전송 지연 개선",
    epicId: "OPR2-1236",
    epicUrl: "https://jira.example.com/browse/OPR2-1236",
    activeTicketCount: 40,
    updatedCount: 12,
    completedCount: 12,
    createdCount: 12,
    createdAt: "2025.10.10",
  },
  {
    id: "4",
    name: "데이터베이스 성능 최적화",
    epicId: "OPR2-1237",
    epicUrl: "https://jira.example.com/browse/OPR2-1237",
    activeTicketCount: 65,
    updatedCount: 15,
    completedCount: 15,
    createdCount: 15,
    createdAt: "2025.10.12",
  },
  {
    id: "5",
    name: "API 응답 시간 개선",
    epicId: "OPR2-1238",
    epicUrl: "https://jira.example.com/browse/OPR2-1238",
    activeTicketCount: 24,
    updatedCount: 6,
    completedCount: 6,
    createdCount: 6,
    createdAt: "2025.10.14",
  },
  {
    id: "6",
    name: "로그인 보안 강화",
    epicId: "OPR2-1239",
    epicUrl: "https://jira.example.com/browse/OPR2-1239",
    activeTicketCount: 36,
    updatedCount: 9,
    completedCount: 9,
    createdCount: 9,
    createdAt: "2025.10.16",
  },
  {
    id: "7",
    name: "모바일 앱 크래시 수정",
    epicId: "OPR2-1240",
    epicUrl: "https://jira.example.com/browse/OPR2-1240",
    activeTicketCount: 41,
    updatedCount: 11,
    completedCount: 11,
    createdCount: 11,
    createdAt: "2025.10.18",
  },
  {
    id: "8",
    name: "검색 기능 버그 수정",
    epicId: "OPR2-1241",
    epicUrl: "https://jira.example.com/browse/OPR2-1241",
    activeTicketCount: 15,
    updatedCount: 4,
    completedCount: 4,
    createdCount: 4,
    createdAt: "2025.10.20",
  },
  {
    id: "9",
    name: "파일 업로드 오류 해결",
    epicId: "OPR2-1242",
    epicUrl: "https://jira.example.com/browse/OPR2-1242",
    activeTicketCount: 25,
    updatedCount: 7,
    completedCount: 7,
    createdCount: 7,
    createdAt: "2025.10.22",
  },
  {
    id: "10",
    name: "이메일 발송 장애 복구",
    epicId: "OPR2-1243",
    epicUrl: "https://jira.example.com/browse/OPR2-1243",
    activeTicketCount: 33,
    updatedCount: 10,
    completedCount: 10,
    createdCount: 10,
    createdAt: "2025.10.24",
  },
  {
    id: "11",
    name: "주문 처리 지연 해결",
    epicId: "OPR2-1244",
    epicUrl: "https://jira.example.com/browse/OPR2-1244",
    activeTicketCount: 40,
    updatedCount: 13,
    completedCount: 13,
    createdCount: 13,
    createdAt: "2025.10.26",
  },
  {
    id: "12",
    name: "캐시 서버 장애 대응",
    epicId: "OPR2-1245",
    epicUrl: "https://jira.example.com/browse/OPR2-1245",
    activeTicketCount: 28,
    updatedCount: 8,
    completedCount: 8,
    createdCount: 8,
    createdAt: "2025.10.28",
  },
];
